[package]
name = "telegraph"
version = "0.1.0"
authors = ["Shane Qi <qizengtai@gmail.com>"]

[dependencies]
hyper = "0.11.2"
tokio-core = "0.1.9"
hyper-tls = "0.1.2"
futures = "0.1.14"
serde = "1.0.11"
serde_json = "1.0.2"
serde_derive = "1.0.11"
handlebars = "0.29.1"